version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: car-service
    restart: unless-stopped
    ports:
      - '8080:8080'
    environment:
      - SERVER_PORT=8080
      - ENVIRONMENT=development
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=john
      - DB_PASSWORD=doe
      - DB_NAME=car_service
      - DB_SSLMODE=disable
    depends_on:
      - postgres
    networks:
      - car-network

  postgres:
    image: postgres:16-alpine
    container_name: postgres
    restart: unless-stopped
    environment:
      - POSTGRES_USER=john
      - POSTGRES_PASSWORD=doe
      - POSTGRES_DB=car_service
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./migrations:/docker-entrypoint-initdb.d
    networks:
      - car-network

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@example.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - '5050:80'
    depends_on:
      - postgres
    networks:
      - car-network

networks:
  car-network:
    driver: bridge

volumes:
  postgres_data:
